### Credentials

#### Name : Mayank Anand
#### Registration Number : 2141001045
#### E-mail : mayankanand2701@gmail.com

###  Code to calculate the Bayes Theorem

In [36]:
def bayesTheorem(ba,a,b):
    res=(ba*a)/b
    print("The Posterior Probability [ P(A|B) ] is : ",res)

# Input 

ba=float(input("Enter the value of P(B|A) : "))
a=float(input("Enter the value of P(A) : "))
b=float(input("Enter the value of P(B) : "))

bayesTheorem(ba,a,b)

Enter the value of P(B|A) : 3
Enter the value of P(A) : 4
Enter the value of P(B) : 5
The Posterior Probability [ P(A|B) ] is :  2.4


### Code to calculate Eigen Value and Eigen Vector of a Matrix

In [37]:
import numpy as np

In [38]:
# 3 x 3 Matrix

matrix=[[1,2,3],[4,5,6],[7,8,9]]

array=np.array(matrix)
x,y=np.linalg.eig(array) 

In [39]:
# to print eigen values 

print("Eigen Values of the given Matrix is :\n",x) 

Eigen Values of the given Matrix is :
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [40]:
# to print eigen vectors

print("Eigen Vectors of the given Matrix is :\n",y)

Eigen Vectors of the given Matrix is :
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Code to calculate Determinant of a Matrix

In [41]:
matrix=[[1,2,3],[4,5,6],[7,2,9]]
array=np.array(matrix)

det = np.linalg.det(array) 

# to print the determinant
print("Determinant of the given Matrix is : ",det) 

Determinant of the given Matrix is :  -36.0


### Code to calculate the Inverse of a Matrix

In [42]:
matrix=[[1,2,3],[4,5,6],[7,2,9]]
array=np.array(matrix)

det = np.linalg.det(array) 

if det==0:
    print("Inverse do not exist for the given matrix.")
else:
    print(np.linalg.inv(array))

[[-0.91666667  0.33333333  0.08333333]
 [-0.16666667  0.33333333 -0.16666667]
 [ 0.75       -0.33333333  0.08333333]]
